version: "3.9"
services:
  db:
    image: postgres:15
    container_name: boilerplate_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: boilerplate
    ports:
      - "5432:5432" # host:container mapping
    volumes:
      - db_data:/var/lib/postgresql/data # persistent storage

  backend:
    build: ./app
    container_name: boilerplate_backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/boilerplate
    ports:
      - "4000:4000"
    depends_on:
      - db

  # frontend:
  #   build: ./frontend
  #   container_name: boilerplate_frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend

volumes:
  db_data:
